"""Phase 3 — safe context generator.

Walks Python source via the stdlib `ast` module and emits a redacted markdown view safe
to paste into an LLM:
- Function/method bodies replaced with `...` (stub-file convention).
- Module-level UPPER_SNAKE constants holding Dict/List/Set/Tuple literals replaced with `...`
  (this is the "proprietary tables" pattern from the Phase 0 case study).
- Class bodies preserved with method signatures and (per policy) docstrings.
- `--strict` mode (or policy `alias_enums: true`): enum values are aliased to opaque names.
- `--strict` mode also forces `keep_docstrings=False`.

Python-only for now. JS/TS lands in Phase 3.5 via tree-sitter; we'll refactor to a shared
parser interface then.
"""

import ast
from pathlib import Path

from cloak import __version__
from cloak.context.js_redactor import language_for_extension, transform_js_like_source
from cloak.policy import Policy

_ENUM_BASE_NAMES = {"Enum", "IntEnum", "StrEnum", "Flag", "IntFlag"}


def generate(
    paths: list[Path],
    policy: Policy,
    *,
    strict: bool = False,
    repo_root: Path | None = None,
) -> str:
    """Return redacted markdown safe to paste into an LLM."""
    if repo_root is None:
        repo_root = paths[0].parent if paths else Path.cwd()

    # --strict overrides policy: drop docstrings, alias enums, regardless of policy defaults.
    keep_docstrings = policy.context_defaults.keep_docstrings and not strict
    alias_enums = policy.context_defaults.alias_enums or strict

    sections: list[str] = [_header(policy, strict=strict)]

    py_files: list[Path] = []
    js_like_files: list[Path] = []
    unsupported_files: list[Path] = []
    for p in paths:
        if not p.is_file():
            continue
        if p.suffix == ".py":
            py_files.append(p)
        elif language_for_extension(p.suffix) is not None:
            js_like_files.append(p)
        else:
            unsupported_files.append(p)

    sections.append(_file_tree(py_files + js_like_files + unsupported_files, repo_root))

    for path in py_files:
        sections.append(
            _python_section(
                path,
                repo_root=repo_root,
                keep_docstrings=keep_docstrings,
                alias_enums=alias_enums,
            )
        )

    for path in js_like_files:
        sections.append(_js_like_section(path, repo_root=repo_root))

    if unsupported_files:
        sections.append(_unsupported_files_note(unsupported_files, repo_root))

    return "\n\n".join(sections) + "\n"


def _header(policy: Policy, *, strict: bool) -> str:
    policy_src = str(policy.source) if policy.source else "defaults"
    strict_note = (
        "\n\nThis is `--strict` mode: enum values are aliased and docstrings are stripped."
        if strict
        else ""
    )
    return (
        f"<!-- generated by cloak {__version__}; "
        f"policy: {policy_src}; strict: {str(strict).lower()} -->\n"
        f"# Safe context\n\n"
        f"This is a redacted view of the source, suitable for sharing with an LLM. "
        f"Function and method bodies are replaced "
        f"(with `...` in Python, `/* [REDACTED BY CLOAK] */` in JS/TS). "
        f"Module-level UPPER_SNAKE_CASE constants holding object/array/dict literals "
        f"are redacted. Imports, class shapes, and signatures are preserved."
        f"{strict_note}"
    )


def _file_tree(files: list[Path], repo_root: Path) -> str:
    if not files:
        return "## Files\n\n_(none)_"
    rels = sorted({_safe_rel(f, repo_root) for f in files})
    body = "\n".join(rels)
    return f"## Files\n\n```\n{body}\n```"


def _python_section(
    path: Path,
    *,
    repo_root: Path,
    keep_docstrings: bool,
    alias_enums: bool,
) -> str:
    rel = _safe_rel(path, repo_root)
    try:
        text = path.read_text(encoding="utf-8")
    except OSError as e:
        return f"## `{rel}`\n\n_(unreadable: {e})_"

    try:
        tree = ast.parse(text)
    except SyntaxError as e:
        return f"## `{rel}`\n\n_(parse error: {e.msg})_"

    redactor = _Redactor(keep_docstrings=keep_docstrings, alias_enums=alias_enums)
    redacted = redactor.visit(tree)
    ast.fix_missing_locations(redacted)
    return f"## `{rel}`\n\n```python\n{ast.unparse(redacted)}\n```"


def _js_like_section(path: Path, *, repo_root: Path) -> str:
    rel = _safe_rel(path, repo_root)
    kind = language_for_extension(path.suffix)
    if kind is None:  # pragma: no cover — caller already filtered.
        return f"## `{rel}`\n\n_(unsupported language)_"
    try:
        text = path.read_text(encoding="utf-8")
    except OSError as e:
        return f"## `{rel}`\n\n_(unreadable: {e})_"

    redacted = transform_js_like_source(text, kind)
    fence_lang = (
        "tsx" if kind == "tsx" else ("typescript" if kind == "typescript" else "javascript")
    )
    return f"## `{rel}`\n\n```{fence_lang}\n{redacted}\n```"


def _unsupported_files_note(files: list[Path], repo_root: Path) -> str:
    rels = sorted(_safe_rel(f, repo_root) for f in files)
    items = "\n".join(f"- `{r}`" for r in rels)
    return (
        "## Files not parsed\n\n"
        "These files were discovered but are not currently supported by `cloak context`:\n\n"
        f"{items}"
    )


def _safe_rel(p: Path, repo_root: Path) -> str:
    try:
        return str(p.resolve().relative_to(repo_root.resolve()))
    except ValueError:
        return str(p)


class _Redactor(ast.NodeTransformer):
    """Redact function bodies, sensitive module-level tables, and (optionally) enum values."""

    def __init__(self, *, keep_docstrings: bool, alias_enums: bool) -> None:
        self.keep_docstrings = keep_docstrings
        self.alias_enums = alias_enums

    # --- function/method body redaction -------------------------------------------------

    def visit_FunctionDef(self, node: ast.FunctionDef) -> ast.AST:
        return self._redact_callable(node)

    def visit_AsyncFunctionDef(self, node: ast.AsyncFunctionDef) -> ast.AST:
        return self._redact_callable(node)

    def _redact_callable(self, node: ast.FunctionDef | ast.AsyncFunctionDef) -> ast.AST:
        new_body: list[ast.stmt] = []
        if self.keep_docstrings and _is_docstring(node.body[0] if node.body else None):
            new_body.append(node.body[0])
        # `...` ellipsis as the body — Python stub-file convention. Unparses cleanly.
        new_body.append(ast.Expr(value=ast.Constant(value=Ellipsis)))
        node.body = new_body
        return node

    # --- class redaction (preserve method shapes; optionally alias enum values) ---------

    def visit_ClassDef(self, node: ast.ClassDef) -> ast.AST:
        if self.alias_enums and _is_enum_class(node):
            return self._alias_enum_class(node)

        new_body: list[ast.stmt] = []
        for i, stmt in enumerate(node.body):
            if i == 0 and _is_docstring(stmt):
                if self.keep_docstrings:
                    new_body.append(stmt)
                continue
            visited = self.visit(stmt)
            if isinstance(visited, ast.stmt):
                new_body.append(visited)
        node.body = new_body or [ast.Pass()]
        return node

    def _alias_enum_class(self, node: ast.ClassDef) -> ast.ClassDef:
        new_body: list[ast.stmt] = []
        i = 0
        if i < len(node.body) and _is_docstring(node.body[i]):
            if self.keep_docstrings:
                new_body.append(node.body[i])
            i += 1

        counter = 0
        for stmt in node.body[i:]:
            if (
                isinstance(stmt, ast.Assign)
                and len(stmt.targets) == 1
                and isinstance(stmt.targets[0], ast.Name)
                and isinstance(stmt.value, ast.Constant)
            ):
                aliased = ast.Assign(
                    targets=[ast.Name(id=f"VALUE_{counter}", ctx=ast.Store())],
                    value=ast.Constant(value=f"V{counter}"),
                )
                new_body.append(aliased)
                counter += 1
            else:
                new_body.append(stmt)
        node.body = new_body or [ast.Pass()]
        return node

    # --- module-level: redact UPPER_SNAKE table constants ------------------------------

    def visit_Module(self, node: ast.Module) -> ast.AST:
        new_body: list[ast.stmt] = []
        for i, stmt in enumerate(node.body):
            if i == 0 and _is_docstring(stmt):
                if self.keep_docstrings:
                    new_body.append(stmt)
                continue

            if _is_proprietary_table(stmt):
                # _is_proprietary_table guarantees stmt is an ast.Assign.
                assert isinstance(stmt, ast.Assign)
                redacted = ast.Assign(
                    targets=stmt.targets,
                    value=ast.Constant(value=Ellipsis),
                )
                new_body.append(redacted)
                continue

            visited = self.visit(stmt)
            if isinstance(visited, ast.stmt):
                new_body.append(visited)
        node.body = new_body
        return node


def _is_docstring(stmt: ast.stmt | None) -> bool:
    return (
        isinstance(stmt, ast.Expr)
        and isinstance(stmt.value, ast.Constant)
        and isinstance(stmt.value.value, str)
    )


def _is_enum_class(node: ast.ClassDef) -> bool:
    for base in node.bases:
        if isinstance(base, ast.Name) and base.id in _ENUM_BASE_NAMES:
            return True
        if isinstance(base, ast.Attribute) and base.attr in _ENUM_BASE_NAMES:
            return True
    return False


def _is_proprietary_table(stmt: ast.stmt) -> bool:
    """Heuristic: module-level UPPER_SNAKE (or _UPPER_SNAKE) name = {dict/list/set/tuple}."""
    if not isinstance(stmt, ast.Assign) or len(stmt.targets) != 1:
        return False
    target = stmt.targets[0]
    if not isinstance(target, ast.Name):
        return False
    name = target.id.lstrip("_")
    if not name or not name.replace("_", "").isupper() or not any(c.isalpha() for c in name):
        return False
    return isinstance(stmt.value, (ast.Dict, ast.List, ast.Set, ast.Tuple))
