"""Tests for `cloak context` (Phase 3)."""

import json
from pathlib import Path

from typer.testing import CliRunner

from cloak.cli import app
from cloak.context.generator import generate
from cloak.policy import Policy

runner = CliRunner()


def _sample_python(tmp_path: Path) -> Path:
    """Module docstring + enum + dataclass + proprietary table + class with methods."""
    repo = tmp_path / "repo"
    repo.mkdir()
    (repo / "pricing.py").write_text(
        '''"""Pricing engine. Proprietary."""

from dataclasses import dataclass
from enum import Enum


class Region(str, Enum):
    NORTHEAST = "NE"
    WEST = "W"


@dataclass
class Customer:
    customer_id: str
    region: Region


_TIER_DISCOUNTS = {
    "low": 0.0,
    "high": 0.15,
}


class Engine:
    """Pricing engine."""

    def calculate(self, customer: Customer) -> float:
        """Return the price for a customer."""
        secret_constant = 1234567890
        return secret_constant * 0.5
'''
    )
    return repo


def test_default_redacts_function_bodies(tmp_path: Path) -> None:
    repo = _sample_python(tmp_path)
    files = list((repo).glob("*.py"))
    md = generate(files, Policy(), repo_root=repo)

    # Body content gone
    assert "secret_constant = 1234567890" not in md
    assert "1234567890" not in md
    # Signature kept
    assert "def calculate(self, customer: Customer) -> float:" in md
    # Docstring kept by default
    assert "Return the price for a customer." in md
    # Body replaced with ellipsis
    assert "..." in md


def test_default_redacts_proprietary_tables(tmp_path: Path) -> None:
    repo = _sample_python(tmp_path)
    files = list((repo).glob("*.py"))
    md = generate(files, Policy(), repo_root=repo)

    assert "_TIER_DISCOUNTS = ..." in md
    # The actual values must NOT leak
    assert "0.15" not in md
    assert '"high"' not in md or md.count('"high"') == 0


def test_default_keeps_enum_values(tmp_path: Path) -> None:
    repo = _sample_python(tmp_path)
    files = list((repo).glob("*.py"))
    md = generate(files, Policy(), repo_root=repo)

    assert "NORTHEAST" in md
    assert "'NE'" in md or '"NE"' in md


def test_strict_aliases_enum_values(tmp_path: Path) -> None:
    repo = _sample_python(tmp_path)
    files = list((repo).glob("*.py"))
    md = generate(files, Policy(), strict=True, repo_root=repo)

    assert "NORTHEAST" not in md
    assert "'NE'" not in md and '"NE"' not in md
    assert "VALUE_0" in md
    assert "VALUE_1" in md


def test_strict_strips_docstrings(tmp_path: Path) -> None:
    repo = _sample_python(tmp_path)
    files = list((repo).glob("*.py"))
    md = generate(files, Policy(), strict=True, repo_root=repo)

    assert "Pricing engine. Proprietary." not in md  # module docstring gone
    assert "Pricing engine." not in md  # class docstring gone
    assert "Return the price for a customer." not in md  # method docstring gone


def test_header_is_stable_and_self_describing(tmp_path: Path) -> None:
    repo = _sample_python(tmp_path)
    files = list((repo).glob("*.py"))
    md = generate(files, Policy(), strict=False, repo_root=repo)

    assert md.startswith("<!--")
    assert "generated by cloak" in md
    assert "strict: false" in md


def test_cli_writes_to_out_and_clipboard_options(tmp_path: Path) -> None:
    repo = _sample_python(tmp_path)
    out_file = tmp_path / "context.md"
    result = runner.invoke(app, ["context", str(repo), "--out", str(out_file)])
    assert result.exit_code == 0
    assert out_file.exists()
    content = out_file.read_text()
    assert "## `pricing.py`" in content
    assert "1234567890" not in content


def test_cli_json_status_mode(tmp_path: Path) -> None:
    repo = _sample_python(tmp_path)
    result = runner.invoke(app, ["context", str(repo), "--json"])
    assert result.exit_code == 0
    payload = json.loads(result.stdout)
    assert payload["command"] == "context"
    assert payload["status"] == "ok"
    assert payload["strict"] is False


def test_cli_default_prints_to_stdout(tmp_path: Path) -> None:
    repo = _sample_python(tmp_path)
    result = runner.invoke(app, ["context", str(repo)])
    assert result.exit_code == 0
    assert "## `pricing.py`" in result.stdout
    # Critical: secret value must not appear
    assert "1234567890" not in result.stdout


def test_unparseable_python_does_not_crash(tmp_path: Path) -> None:
    repo = tmp_path / "repo"
    repo.mkdir()
    (repo / "broken.py").write_text("def broken(:::\n")
    result = runner.invoke(app, ["context", str(repo)])
    assert result.exit_code == 0
    assert "parse error" in result.stdout.lower()


def test_non_python_files_listed_separately(tmp_path: Path) -> None:
    repo = tmp_path / "repo"
    repo.mkdir()
    (repo / "main.py").write_text("def f(): return 1\n")
    (repo / "config.toml").write_text("[settings]\nx = 1\n")
    result = runner.invoke(app, ["context", str(repo)])
    assert result.exit_code == 0
    assert "Files not parsed" in result.stdout
    assert "config.toml" in result.stdout
