"""`cloak policy init` — scaffold a starter .cloakpolicy for the current project."""

from dataclasses import dataclass, field
from pathlib import Path

# Files that signal a particular ecosystem when sitting at repo root.
_PYTHON_MARKERS = ("pyproject.toml", "setup.py", "setup.cfg", "Pipfile", "poetry.lock")
_NODE_MARKERS = ("package.json", "pnpm-lock.yaml", "yarn.lock", "package-lock.json")
_TS_MARKERS = ("tsconfig.json",)

# Common source-tree layouts to suggest as `sensitive_paths`.
_COMMON_SRC_DIRS = ("src", "lib", "app", "packages")


@dataclass
class ProjectDetection:
    """What we figured out about the project we're scaffolding a policy for."""

    has_python: bool = False
    has_node: bool = False
    has_typescript: bool = False
    src_dirs: list[str] = field(default_factory=list)

    @property
    def label(self) -> str:
        parts: list[str] = []
        if self.has_python:
            parts.append("Python")
        if self.has_typescript:
            parts.append("TypeScript")
        elif self.has_node:
            parts.append("JavaScript")
        return " + ".join(parts) or "generic"


def detect_project(root: Path) -> ProjectDetection:
    """Best-effort sniff of the project layout. Cheap; no recursion through node_modules."""
    detection = ProjectDetection()

    for marker in _PYTHON_MARKERS:
        if (root / marker).exists():
            detection.has_python = True
            break
    if not detection.has_python:
        for child in root.iterdir() if root.is_dir() else []:
            if child.is_file() and child.suffix == ".py":
                detection.has_python = True
                break

    for marker in _NODE_MARKERS:
        if (root / marker).exists():
            detection.has_node = True
            break

    for marker in _TS_MARKERS:
        if (root / marker).exists():
            detection.has_typescript = True
            break
    if detection.has_node and not detection.has_typescript:
        # Fallback: if any top-level .ts file exists, treat as TS too.
        for child in root.iterdir() if root.is_dir() else []:
            if child.is_file() and child.suffix in {".ts", ".tsx"}:
                detection.has_typescript = True
                break

    for d in _COMMON_SRC_DIRS:
        if (root / d).is_dir():
            detection.src_dirs.append(f"{d}/**")

    return detection


def build_starter_policy(detection: ProjectDetection) -> str:
    """Produce the YAML text of a sensible-default .cloakpolicy for the detected project."""
    sensitive = detection.src_dirs or ["src/**"]
    sensitive_yaml = "\n".join(f'  - "{p}"' for p in sensitive)

    label = detection.label

    return (
        "# .cloakpolicy — generated by `cloak policy init`.\n"
        f"# Detected project: {label}.\n"
        "# Edit to fit your project, then commit. Whoever can merge this file "
        "controls CLOAK policy.\n"
        "\n"
        "version: 1\n"
        "\n"
        "# Paths CLOAK treats with extra care. Globs match files relative to repo root.\n"
        "sensitive_paths:\n"
        f"{sensitive_yaml}\n"
        "\n"
        "# Names that must NEVER be renamed by `cloak obfuscate`. Add public-API symbols here.\n"
        '# Examples: "QuoteEngine.calculate_quote", "PaymentGateway.*"\n'
        "public_api: []\n"
        "\n"
        "# Custom secret-detection rules layered on top of the built-in scanner.\n"
        "secret_rules: []\n"
        "\n"
        "# Strings safe to keep un-redacted (URLs to public docs, license headers, etc.).\n"
        "allow_strings: []\n"
        "\n"
        "# Default behavior of `cloak context` (redacted markdown for LLM paste).\n"
        "context_defaults:\n"
        "  keep_docstrings: true\n"
        "  redact_function_bodies: true\n"
        "  alias_enums: false           # set true to behave like --strict by default\n"
        "\n"
        "# Default behavior of `cloak obfuscate` (transformed copy for sharing).\n"
        "obfuscate_defaults:\n"
        "  rename_private: true\n"
        "  rename_public_api: false\n"
        "  encode_strings: false        # opt-in only — strings are often SQL/log keys\n"
        "  strip_docstrings: false\n"
        '  profile: standard            # or "aggressive"\n'
    )
